# Generated by Django 4.1.3 on 2022-12-11 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MriSoftware", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="linecse",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MriSoftware.license",
            ),
        ),
    ]
