# Generated by Django 4.1.3 on 2022-12-11 20:44

import MriSoftware.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MriSoftware", "0003_alter_user_linecse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="research",
            name="file",
            field=models.FileField(null=True, upload_to=MriSoftware.models.upload_link),
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=MriSoftware.models.upload_imageOriginal
                    ),
                ),
                (
                    "masked",
                    models.ImageField(upload_to=MriSoftware.models.upload_imageMasked),
                ),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MriSoftware.research",
                    ),
                ),
            ],
        ),
    ]
