# Generated by Django 4.1.3 on 2022-12-11 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MriSoftware", "0004_alter_research_file_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(upload_to="media/imageoriginal/"),
        ),
        migrations.AlterField(
            model_name="images",
            name="research",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MriSoftware.research",
            ),
        ),
    ]
