# Generated by Django 4.1.3 on 2022-12-12 10:02

import MriSoftware.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MriSoftware", "0005_alter_images_image_alter_images_research"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(upload_to=MriSoftware.models.upload_imageOriginal),
        ),
    ]
