# Generated by Django 4.1.3 on 2022-12-13 13:03

import MriSoftware.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MriSoftware", "0007_alter_images_image_alter_images_masked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="research",
            name="report",
            field=models.FileField(
                max_length=200, null=True, upload_to=MriSoftware.models.upload_link
            ),
        ),
    ]
