# Generated by Django 4.1.3 on 2023-02-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MriSoftware", "0008_research_report"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctors",
            options={"ordering": ["name", "second_name", "profession"]},
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"ordering": ["name", "second_name", "pass_number"]},
        ),
        migrations.AlterModelOptions(
            name="research",
            options={"ordering": ["date_research", "doctor"]},
        ),
    ]
